"use client";

import React from "react";
import Link from "next/link";
import { Activity } from "lucide-react";
import { AnalysisResults } from "@/components/analysis/AnalysisResults";
import type {
  UXAnalysis,
  ConversionAnalysis,
  MonetizationAnalysis,
  BenchmarkAnalysis,
  Recommendation,
} from "@/types";

interface SharedAnalysisViewProps {
  url: string;
  domain: string;
  executiveSummary?: string;
  uxAnalysis?: UXAnalysis;
  conversionAnalysis?: ConversionAnalysis;
  monetizationAnalysis?: MonetizationAnalysis;
  benchmarkAnalysis?: BenchmarkAnalysis;
  recommendations?: Recommendation[];
  createdAt: string;
}

export function SharedAnalysisView({
  url,
  domain,
  executiveSummary,
  uxAnalysis,
  conversionAnalysis,
  monetizationAnalysis,
  benchmarkAnalysis,
  recommendations,
  createdAt,
}: SharedAnalysisViewProps) {
  return (
    <div className="min-h-screen app-shell-bg">
      {/* Shared Header */}
      <header className="border-b border-[var(--border-subtle)] bg-[var(--bg-deep)]/80 backdrop-blur-md sticky top-0 z-30">
        <div className="max-w-5xl mx-auto px-6 py-4 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-[var(--radius-sm)] bg-[var(--accent-dim)] border border-amber-300/20 flex items-center justify-center">
              <Activity className="w-3.5 h-3.5 text-white" />
            </div>
            <span className="text-base font-bold text-[var(--text-primary)]">
              Growth<span className="text-amber-400">Lens</span>
            </span>
          </Link>
          <div className="text-right">
            <p className="text-xs text-[var(--text-dim)] font-mono">Shared Report</p>
            <p className="text-xs text-[var(--text-muted)]">
              {new Date(createdAt).toLocaleDateString("en-US", {
                year: "numeric",
                month: "short",
                day: "numeric",
              })}
            </p>
          </div>
        </div>
      </header>

      <main className="max-w-5xl mx-auto px-6 py-8">
        <div className="mb-6">
          <h1 className="text-2xl font-bold text-[var(--text-primary)]">
            Analysis: <span className="text-amber-400">{domain}</span>
          </h1>
          <p className="text-sm text-[var(--text-muted)] mt-1">{url}</p>
        </div>

        <AnalysisResults
          executiveSummary={executiveSummary}
          uxAnalysis={uxAnalysis}
          conversionAnalysis={conversionAnalysis}
          monetizationAnalysis={monetizationAnalysis}
          benchmarkAnalysis={benchmarkAnalysis}
          recommendations={recommendations}
          domain={domain}
          url={url}
        />

        {/* CTA Banner */}
        <div className="mt-12 p-6 rounded-[var(--radius-md)] bg-[var(--accent-dim)] border border-amber-300/20 text-center">
          <p className="text-sm text-amber-200">
            This report was generated by{" "}
            <Link href="/" className="font-semibold text-amber-300 hover:underline">
              GrowthLens
            </Link>
            {" "}— AI-Powered Product Growth Analyzer
          </p>
          <Link href="/auth/signup" className="inline-block mt-3 px-5 py-2 bg-[var(--accent)] text-black text-sm font-semibold rounded-[var(--radius-sm)] hover:brightness-110 transition-all">
            Analyze Your Product Free
          </Link>
        </div>
      </main>
    </div>
  );
}
